### ISSUE TITLE
ContainerDuration is not set in jid-writer.cpp

### ISSUE THREAD

**Issue by ashleymannersbackup** [sandflow/jid#16]
On line 780, was the intention to set the ContainerDuration to an empty optional?

The current code `desc->ContainerDuration.empty();` calls a getter so doesn't actually do anything.
I think perhaps this was meant to be `desc->ContainerDuration.set(0);` or `desc->ContainerDuration.reset(0);`

**Comment by palemieux** [comment]
Isn't set here in the footer?

https://github.com/cinecert/asdcplib/blob/d417531ed59434ecaee487adfdf54646408479bf/src/AS_02_internal.h#L236

**Comment by ashleymannersbackup** [comment]
Ah, you're right Pierre. It is set in the footer.
The title of my bug is a bit misleading.

I just meant that line 780 isn't actually doing anything so could be removed. Just wanted to make sure it wasn't supposed to be setting the ContainerDuration.

Happy to close this without any change as it doesn't have any affect on usage.

**Comment by palemieux** [comment]
Per ST 377-1, F.2, _If it cannot be completed, [Container Duration] should be omitted._

> I just meant that line 780 isn't actually doing anything so could be removed.

Are we sure ASDCP does not set it to 0 by default? Maybe it did at some point, or maybe that line was added as a prophylactic.

**Comment by palemieux** [comment]
> The current code desc->ContainerDuration.empty(); calls a getter so doesn't actually do anything.

Replaced with `desc->ContainerDuration.set_has_value(false)` at https://github.com/sandflow/jid/pull/17

**Comment by ashleymannersbackup** [comment]
> > The current code desc->ContainerDuration.empty(); calls a getter so doesn't actually do anything.
> 
> Replaced with `desc->ContainerDuration.set_has_value(false)` at #17

Great.  That solves the issue.  Thanks!
