### ISSUE TITLE
Feature Request: Mastering Display Metadata

### ISSUE THREAD

**Issue by anderson1077** [sandflow/jid#27]
Could we please add the capability to inject the optional mastering display ~~and active picture area~~ metadata into the MXF at wrap time? These would be extremely helpful for handoff to a number of authoring and validation services.

ULs:
060e2b34.0101010e.04200401.01040000 GenericPictureEssenceDescriptor_MasteringDisplayMinimumLuminance
060e2b34.0101010e.04200401.01030000 GenericPictureEssenceDescriptor_MasteringDisplayMaximumLuminance
060e2b34.0101010e.04200401.01020000 GenericPictureEssenceDescriptor_MasteringDisplayWhitePointChromaticity
060e2b34.0101010e.04200401.01010000 GenericPictureEssenceDescriptor_MasteringDisplayPrimaries

**Comment by palemieux** [comment]
Support for Display and Active rectangles moved to #28
