### ISSUE TITLE
The version of "OpenSSL"

### ISSUE THREAD

**Issue by miaoqiz** [sandflow/jid#3]
Hi there,

Thanks for the repository!

Can you kindly let us know what version of "OpenSSL" that you used?

For example, in the newer release, "libeay32" may be replaced by "libssl" etc. Also, the header files need to match, otherwise, there are linking issues such as:

--------------------------------------------------------------------------------

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __iob_func referenced in function OPENSSL_showfatal	as-02-info	C:\Users\Admin\Downloads\jid-master\build\lib\asdcplib\src\libeay32.lib(cryptlib.obj)	1	
Error	LNK2019	unresolved external symbol vfprintf referenced in function OPENSSL_showfatal	as-02-info	C:\Users\Admin\Downloads\jid-master\build\lib\asdcplib\src\libeay32.lib(cryptlib.obj)	1	
Error	LNK2019	unresolved external symbol _vsnwprintf referenced in function OPENSSL_showfatal	as-02-info	C:\Users\Admin\Downloads\jid-master\build\lib\asdcplib\src\libeay32.lib(cryptlib.obj)	1	
Error	LNK1120	3 unresolved externals	as-02-info	C:\Users\Admin\Downloads\jid-master\build\lib\asdcplib\src\Debug\as-02-info.exe	1	

--------------------------------------------------------------------------------

Thanks

**Comment by palemieux** [comment]
Which OS/version are your targeting?

**Comment by miaoqiz** [comment]
Windows 10. 

Also, in the "CMakelist.txt" inside "asdcplib":

-----------------------------------------------------------------------
find_library(OpenSSLLib_PATH NAMES libeay32 crypto PATHS "${PROJECT_SOURCE_DIR}/../openssl" "${PROJECT_SOURCE_DIR}/../lib/openssl" "$ENV{CMAKE_HINT}/openssl" ENV CMAKE_HINT PATH_SUFFIXES "lib" "openssl" "lib/openssl")
find_path(OpenSSLLib_include_DIR NAMES openssl/rand.h PATHS "${PROJECT_SOURCE_DIR}/../openssl" "${PROJECT_SOURCE_DIR}/../lib/openssl" "$ENV{CMAKE_HINT}/openssl" ENV CMAKE_HINT PATH_SUFFIXES "include" "inc32")
find_library(XercescppLib_PATH NAMES xerces-c xerces-c_3 PATHS "${PROJECT_SOURCE_DIR}/../xercescpp" "${PROJECT_SOURCE_DIR}/../lib/xercescpp" "$ENV{CMAKE_HINT}/xercescpp" ENV CMAKE_HINT PATH_SUFFIXES "lib")
find_library(XercescppLib_Debug_PATH NAMES xerces-cD xerces-c_3D xerces-c PATHS "${PROJECT_SOURCE_DIR}/../xercescpp" "${PROJECT_SOURCE_DIR}/../lib/xercescpp" "$ENV{CMAKE_HINT}/xercescpp" ENV CMAKE_HINT PATH_SUFFIXES "lib")
find_path(XercescppLib_include_DIR NAMES xercesc/dom/DOM.hpp PATHS "${PROJECT_SOURCE_DIR}/../xercescpp" "${PROJECT_SOURCE_DIR}/../lib/xercescpp" "$ENV{CMAKE_HINT}/xercescpp" ENV CMAKE_HINT PATH_SUFFIXES "include")

-----------------------------------------------------------------------

Even I specified the right paths, it still cannot find the "lib". So I had to manually set the paths.

**Comment by palemieux** [comment]
On Win10, I use ` OpenSSL 1.0.2t 10 Sep 2019`, and have the following paths: 

![Annotation 2020-03-27 194711](https://user-images.githubusercontent.com/4871350/77813187-cbb60b80-7063-11ea-8300-290b7d24e469.png)

I recommend not modifying `CMakelist.txt` directly. I instead use CMake GUI on Windows or define the path on the command line.

FYI `Win64 OpenSSL v1.0.2u` can be downloaded at https://slproweb.com/products/Win32OpenSSL.html

**Comment by miaoqiz** [comment]
Thanks. Will do!

**Comment by palemieux** [comment]
@miaoqiz Ok. Let me know if it works for you, and I will update the README accordingly.

**Comment by miaoqiz** [comment]
Hi,

Thanks for your suggestion. I installed "Win64 OpenSSL v1.0.2u", now the issue is gone.

However, "dcdm2imf" is still to be finished due to the following linking error:

----------------------------------------------------------------------------------

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libboost_program_options-vc141-mt-gd-x64-1_66.lib'	dcdm2imf	C:\Users\Admin\Downloads\jid-master\build\LINK	1	

----------------------------------------------------------------------------------

I compiled "boost_1_66_0" and set the "Boost_INCLUDE_DIR" to be the root directory of "boost_1_66_0". Not sure if you need "BoostLib_PATH" because of "target_link_libraries(${PROJECT_NAME} ${Boost_LIBRARIES} libas02)" in "CMakelists.txt" in the root, so I added "boost_1_66_0/stage/lib". Still there is no such as library during the linking stage. 


Thanks!

**Comment by palemieux** [comment]
Here's what I have configured for boost:

![Annotation 2020-03-29 110403](https://user-images.githubusercontent.com/4871350/77856599-13947a00-71ad-11ea-88d3-d00d0c0f9d4d.png)

... and my boost directory looks like:

![Annotation 2020-03-29 110403](https://user-images.githubusercontent.com/4871350/77856610-30c94880-71ad-11ea-8d16-170cf3a0af57.png)

**Comment by miaoqiz** [comment]
Thanks so much! It is built. :)

Have a good day and stay safe!
